#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#test:
#    path: /test
#    controller: App\Controller\TestController::index

get_phone_number:
    path: /getphonenumber
    controller: App\Controller\GetPhoneNumberController::index