#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#test:
#    path: /test
#    controller: App\Controller\TestController::index

get_phone_number:
    path: /user/v1/getphonenumber
    controller: App\UserContext\Presentation\Query\GetPhoneNumberController::index