#!/usr/bin/env bash

# Author: Nicolas Giraud <nicolas.giraud.dev@gmail.com>
# Copyright (c) 2017
# License: MIT

set -o errexit  # Make your script exit when a command fails.
set -o pipefail # Catch 'xxx' fails for command 'xxx|yyy'.
set -o nounset  # Exit script when using unset variable.
#set -o xtrace   # Debug mode. Uncomment to activate.

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"

# Set the URL registry where the docker image to based on is stored.
REGISTRY="nicodocker91/phpmetrics:7.2"

# Set dynamic options for the command:
# - Enable the --tty option if there is a tty.
option_tty=$(if [ "not a tty" = "$(tty)" ]; then echo ""; else echo " --tty "; fi)

# Build the reports folder where logs will be stored.
QA_BUILD_FOLDER=${QA_BUILD_FOLDER:-${__root}/data/build}
REPORTS_FOLDER="${QA_BUILD_FOLDER}/user/$(date +'%Y%m%d0000')/logs/phpmetrics"
mkdir -p ${REPORTS_FOLDER} 2>/dev/null

PATHS_TO_COMPUTE="www/composer.json,www/src/UserContext"
[[ -f www/composer.lock ]] && PATHS_TO_COMPUTE="${PATHS_TO_COMPUTE},www/composer.lock"

JUNIT_REPORT=""
[[ -f ${REPORTS_FOLDER}/../phpunit/phpunit-unit.xml ]] && JUNIT_REPORT="--junit=${REPORTS_FOLDER}/../phpunit/phpunit-unit.xml"

# Run the docker command.
docker run --rm ${option_tty} \
    --user $(id -u):$(id -g) \
    --volume ${__root}:/data/www \
    --volume ${REPORTS_FOLDER}/..:${REPORTS_FOLDER}/.. \
    ${REGISTRY} \
        --exclude=Tests,tests,.svn,.git,vendor,InfrastructureBundle \
        --git \
        ${JUNIT_REPORT} \
        --report-html=${REPORTS_FOLDER} \
        ${PATHS_TO_COMPUTE}
