#!/usr/bin/env bash

# Author: Nicolas Giraud <nicolas.giraud.dev@gmail.com>
# Copyright (c) 2017
# License: MIT

set -o errexit  # Make your script exit when a command fails.
set -o pipefail # Catch 'xxx' fails for command 'xxx|yyy'.
set -o nounset  # Exit script when using unset variable.
#set -o xtrace   # Debug mode. Uncomment to activate.

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"

# Set the URL registry where the docker image to based on is stored.
REGISTRY="nicodocker91/phpunit:8.0-php7.2"

# Set dynamic options for the command:
# - Enable the --tty option if there is a tty.
option_tty=$(if [ "not a tty" = "$(tty)" ]; then echo ""; else echo " --tty "; fi)

# Build the reports folder where logs will be stored.
QA_BUILD_FOLDER=${QA_BUILD_FOLDER:-${__root}/data/build}
REPORTS_FOLDER="${QA_BUILD_FOLDER}/user/$(date +'%Y%m%d0000')/logs/phpunit"
mkdir -p ${REPORTS_FOLDER} 2>/dev/null

# As phpunit requires composer to be ran, check its existance before running the docker command.
if [ ! -f ${__root}/www/vendor/autoload.php ]; then
    echo "# Composer has not been ran while it is required. Running 'cmd/composer install' command..."
    cmd/composer install
fi
if [ ! -f ${__root}/vendor/autoload.php ]; then
    echo "# Composer install has failed. Cannot run phpunit."
    exit 2
fi

# Run the docker command.
docker run --rm ${option_tty} \
    --user $(id -u):$(id -g) \
    --volume ${__root}:/data/www \
    --volume ${REPORTS_FOLDER}:${REPORTS_FOLDER} \
    ${REGISTRY} \
        --bootstrap=vendor/autoload.php \
        -d memory_limit=-1 \
        --log-junit ${REPORTS_FOLDER}/phpunit-unit.xml \
        --cache-result \
        --cache-result-file ${REPORTS_FOLDER}/cache/.phpunit.result.cache \
        --coverage-clover ${REPORTS_FOLDER}/coverage-clover.xml \
        --coverage-html ${REPORTS_FOLDER}/coverage-html/ \
        --coverage-text \
        --colors=never \
        --whitelist=src/UserContext \
        tests/
