#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_phone_number:
    path: /user/v1/getphonenumber/{name}
    controller: App\UserContext\Presentation\GetPhoneNumber\Query\GetPhoneNumberController::index